services:
  ##########################################
  # govcms: The GovCMS local development
  ##########################################
  govcms:
    build:
      context: .
      dockerfile: .docker/Dockerfile.govcms
    container_name: govcms
    volumes:
      # Source code volumes
      - modules:/app/web/modules/develop
      - themes:/app/web/themes/develop
      - files:/app/web/sites/default/files

      # Test volumes
      - behat:/app/tests/behat
      - cy:/app/tests/cy
      - phpunit:/app/tests/phpunit

      # Composer cache volume
      - composer_cache:/home/govcms/.cache

      # Configuration files
      - ./.docker/config/rector.php:/app/rector.php
    environment:
      - GOVCMS_ENV=development
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.govcms.rule=Host(`govcms.localhost`)"
      - "traefik.http.routers.govcms-http.entrypoints=web"
      - "traefik.http.services.govcms.loadbalancer.server.port=80"
    networks:
      - internal
    ports:
      - "0:80"
    develop:
      watch:
        - action: sync
          path: .
          target: /app/tests
          ignore:
            - vendor/
            - node_modules/
            - app/
            - data/
        - action: rebuild
          path: composer.json

volumes:
  modules:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./app/modules
  themes:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./app/themes
  files:
  behat:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./behat
  cy:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./cy
  phpunit:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./phpunit
  composer_cache:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/composer

networks:
  internal:
    external: false